### ISSUE TITLE
Subscribe to multiple topics / verbose bus monitor method?

### ISSUE THREAD

**Issue by NerdyProjects** [OpenCyphal/yakut#32]
Hey there,

In my "uavcan as housebus" project I am thinking if I should migrate to uavcan v1. In v0, I have the gui tool which works great for configuring and monitoring nodes.

I am now developing my first v1 node and miss anything like the bus monitor.

`yakut` allows me only to subscribe to one port at a time, the `yakut monitor` command only shows traffic statistics but not content. Am I missing something?

**Comment by pavel-kirienko** [comment]
Hi Matthias! You are not missing anything.

Perhaps counterintuitively, this is tracked here: https://github.com/UAVCAN/yakut/issues/1. An outline of the approach is given in this post: https://forum.uavcan.org/t/uavcan-v1-wireshark-plugin/1058/2?u=pavel.kirienko

Basically, we need two commands:

- `yakut capture` to record raw transport frames (Ethernet or CAN frames) from the bus into a binary non-human-readable DSDL-serialized format.
- `yakut trace` to extract messages and service calls from the above.
- Your specific use case would be addressed simply by piping the output of one to the other: `yakut capture | yakut trace`.

It may sound convoluted but actually it is easy to implement because all of the low-level protocol handling is already implemented in PyUAVCAN, we just need a CLI adapter on top:

- https://pyuavcan.readthedocs.io/en/stable/pages/architecture.html#advanced-network-diagnostics-sniffing-snooping-tracing-spoofing
- https://forum.uavcan.org/t/how-to-get-raw-data-from-transport/1386/2?u=pavel.kirienko

Are you available to help us implement this? Do you have experience with Python?

**Comment by pavel-kirienko** [comment]
It is now possible to subscribe to multiple subjects concurrently using `yakut subscribe`.
