### ISSUE TITLE
Usability concerns

### ISSUE THREAD

**Issue by chemicstry** [OpenCyphal/yakut#60]
I don't know if it's just me, but I find the yakut tool a bit inconvenient to use. It requires a lot of initial configuration compared to the old uavcan_gui tool. And this is especially hard for less tech-savvy field operators.

Initial confusion is that the first command given in the README is `yakut --path=/the/path compile path/to/my_namespace --output=destination/directory`. However, I could not understand why it needs 3 paths for compilation. As far as I understand only the arguments and the `--output` paths are used, while `--path` is ignored?

Then README explains to setup environment variables so that default compilation output goes to user data directory. Wouldn't it be better to have this as default instead of current working directory? AFAIK, this is the most common use case.

Would it be possible to ship public regulated data types together with yakut? Or maybe add a command that would download and compile them for you?

Another convienient option would be to load custom DSDLs from user directory and compile them automatically, as was the case with uavcan_gui tool.

I can contribute some of these changes, but firstly wanted to hear some opinions about this.

**Comment by thirtytwobits** [comment]
I agree it is not convenient but it is powerful. This, to me, suggests that something built on top of Yakut would be in order. Perhaps a VSCode plugin that uses Yakut and injects workspace defaults as Yakut defaults, does git pull of the public, regulated types, etc? I think opportunities to simplify the command-line would be accepted (I'm not the maintainer here though) but I don't think it's a good idea to provide any pre-compiled data types or otherwise tightly bind the tool with the types. While gui_tool worked well with little to no configuration the auto-magic defaults quickly became an impediment as our systems matured. I don't want to have that kind of inflexibility nor hidden behaviours in Yakut.

**Comment by chemicstry** [comment]
Just to be clear, I'm not advocating for removing configuration, but for providing convenient defaults instead.

Regarding bundled datatypes, what if `YAKUT_PATH` defaulted to `~/.yakut` (or `%APPDATA%/yakut`) and it would be automatically populated with public types on first launch or with a `yakut install`? Opting out is just changing `YAKUT_PATH`, which you already have to do.

**Comment by pavel-kirienko** [comment]
If we implemented https://github.com/OpenCyphal/pycyphal/issues/153 then the need for `YAKUT_PATH` and `yakut compile` will be obviated completely, which is *great*. Instead of that we will have `CYPHALPATH` that points where DSDL sources are, which may default to `~/.cyphal` or something similar depending on the platform.

Then we could have your `yakut dsdl install` that would by default download DSDL namespaces to, let's say, `~/.cyphal` or maybe the first location specified in `CYPHALPATH` -- we should discuss the specifics later.

I suggest we discuss `yakut setup` later as well, for now it seems reasonable to focus on automatic DSDL compilation. Let's continue this over at https://github.com/OpenCyphal/pycyphal/issues/153
